language: python
python:
    - "2.7"
    - "3.3"
install:
    - pip install nose
    - pip install nose-cov
    - python setup.py install
script: nosetests -sv --with-coverage --cover-package=irctk
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls

